name: BLEmesh2mqtt
version: dev
slug: blemesh2mqtt
description: BLEmesh2mqtt add-on with full access (v1)
url: https://github.com/mtippt/BLEmesh2mqtt
image: "ghcr.io/mtippt/{arch}-blemesh2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_dbus: true
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - SYS_RESOURCE
  - SYS_PTRACE
  - SYS_MODULE
  - DAC_READ_SEARCH
map:
  - share:rw
full_access: true
options:
  message: Hello world...
schema:
  message: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
